name: Fetch latest release version test

on:
  workflow_dispatch:

jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
        
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1

      - name: Set job outputs
        id: set-outputs
        shell: bash
        run: |
          echo "::set-output name=targetTag::$(echo ${{ steps.tag.outputs.tag }})"
          echo "::set-output name=targetCommit::$(echo ${{ github.sha }})"

      - name: Test
        run: echo ${{ steps.fetch-latest-release.outputs.latest-release }}
          
          
          
         


