name: Fetch latest release version test

on:
  workflow_dispatch:
  release:
    types: [published]
    
jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
        

      - name: Fetch latest release version
        id: fetch-latest-release
        run: git describe --tags


      - name: Test
        run: echo ${{ steps.fetch-latest-release.outputs }}
          
          
          
         


