name: Fetch latest release version test

on:
  workflow_dispatch:

    
jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - id: fetch-latest-release
        uses: thebritican/fetch-latest-release@v1
        with:
          github_token: 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
          prerelease: false
      - name: "Print result"
        run: |
          echo "release: ${{ steps.fetch-latest-release }}"
          

          
          
         


