name: Fetch latest release version test

on:
  workflow_dispatch:
  release:
    types: [published]
    
jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Event context
        env:
          EVENT: ${{ toJSON(github.event) }}
        run: |
          echo "$EVENT"
          
          
          
         


