name: Fetch latest release version test

on:
  workflow_dispatch:

jobs:
  build:
    name: aws_demo
    runs-on: ubuntu-latest
    steps:
      - id: aws_demo
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: fredfrazao
          repo: aws_demo
          excludes: prerelease, draft


