name: Fetch latest release version test

on:
  workflow_dispatch:

jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
        

      - name: Set job outputs
        id: set-outputs
        shell: bash
        run: |
          echo "::set-output name=targetCommit::$(echo ${{ github.sha }})"

      - name: Test
        run: echo ${{ steps.set-outputs }}
          
          
          
         


